# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11a29a1247e0002b36e01639036864c1cdafd1c01140a8c81bfa08f2091125e0a4bdfda1f44e0cfe158ab7bec8dc5db0699823ac0a50e9b7de027290b8bb4ca0

test:
  secret_key_base: 9e85329f9dc6fdceb1e147d6e0efd4b457cbdd8e5451280fc430dd7254b5180d2e3a1abb53843051c42adcc6aa63c4fb3cb379149340916a0594d4b9b19551a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
